# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         libintl-perl
version:      1.09
version_from: lib/Locale/TextDomain.pm
installdirs:  site
license:      lgpl
dynamic_config: 1
requires:
	File::Spec: 0
distribution_type: module
generated_by: hand 4u 
