--- #YAML:1.0
# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         libintl-perl
version:      1.11
version_from: lib/Locale/TextDomain.pm
installdirs:  site
requires:
    File::Spec:                    0
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
